export const GET_RANDOM_MEAL_SUCCESS = "GET_RANDOM_MEAL_SUCCESS";
export const GET_RANDOM_MEAL_FAIL = "GET_RANDOM_MEAL_FAIL";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL";